name = "package"
uuid = "87bdded8-9b4f-4ab1-9442-645f17521f7d"
authors = ["DESKTOP-STEJLR5\\vikto <zinkovich.vs@phystech.edu>"]
version = "0.1.0"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
